// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAANZ3BRvWds5FTtRkhgQ4SJSrLzHCjgtw',
//     appId: '1:33147133189:web:40205e2685d89af263ab6c',
//     messagingSenderId: '33147133189',
//     projectId: 'authentication-7aeb1',
//     authDomain: 'authentication-7aeb1.firebaseapp.com',
//     storageBucket: 'authentication-7aeb1.firebasestorage.app',
//     measurementId: 'G-DPEWSWTD2N',
//   );
//
//   // static const FirebaseOptions android = FirebaseOptions(
//   //   apiKey: 'AIzaSyAQELUwee3o15hDurlD1YQc_8NczUhIOjQ',
//   //   appId: '1:33147133189:android:e2899803eed9081d63ab6c',
//   //   messagingSenderId: '33147133189',
//   //   projectId: 'authentication-7aeb1',
//   //   storageBucket: 'authentication-7aeb1.firebasestorage.app',
//   // );
//   //
//   // static const FirebaseOptions ios = FirebaseOptions(
//   //   apiKey: 'AIzaSyCk5QXreaiWq5Kai7ZPYwiaXrtIk7e1_6Q',
//   //   appId: '1:33147133189:ios:a6539a1c98507ff963ab6c',
//   //   messagingSenderId: '33147133189',
//   //   projectId: 'authentication-7aeb1',
//   //   storageBucket: 'authentication-7aeb1.firebasestorage.app',
//   //   iosBundleId: 'com.example.project1',
//   // );
// }
